server:
  port: 8081
  servlet:
    context-path: /api

product:
  jdbc:
    url: jdbc:mysql://localhost:3306/user_roles_db?serverTimezone=UTC

jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  user: root
  pass: rootroot

client.service.auth.url: http://localhost:8085

key:
  location: classpath:key.pub

logging:
  level:
    org:
      springframework:
        security: TRACE