export const C_NOTE_CREATE_IS_IN_PROGRESS = 'C_NOTE_CREATE_IS_IN_PROGRESS';
export const C_NOTE_CREATE_SUCCESS = 'C_NOTE_CREATE_SUCCESS';
export const C_NOTE_CREATE_FAILURE = 'C_NOTE_CREATE_FAILURE';
export const C_NOTE_CREATE_MODAL_SHOW = 'C_NOTE_CREATE_MODAL_SHOW';
export const C_NOTE_CREATE_MODAL_HIDE = 'C_NOTE_CREATE_MODAL_HIDE';

export const C_NOTE_FETCH_IS_LOADING = 'C_NOTE_FETCH_IS_LOADING';
export const C_NOTE_FETCH_LOAD_SUCCESS = 'C_NOTE_FETCH_LOAD_SUCCESS';
export const C_NOTE_FETCH_LOAD_FAILURE = 'C_NOTE_FETCH_LOAD_FAILURE';
export const C_NOTE_FETCH_LOAD_SUCCESS_EMPTY = 'C_NOTE_FETCH_LOAD_SUCCESS_EMPTY';

export const C_NOTES_SEARCH_IS_LOADING = 'C_NOTES_SEARCH_IS_LOADING';
export const C_NOTES_SEARCH_LOAD_SUCCESS = 'C_NOTES_SEARCH_LOAD_SUCCESS';
export const C_NOTES_SEARCH_LOAD_FAILURE = 'C_NOTES_SEARCH_LOAD_FAILURE';
export const C_NOTES_REFRESH_AFTER_UPDATE = 'C_NOTES_REFRESH_AFTER_UPDATE';
export const C_NOTE_SELECT = 'C_NOTE_SELECT';

export const C_NOTE_UPDATE_SUCCESS = 'C_NOTE_UPDATE_SUCCESS';
export const C_NOTE_UPDATE_FAILURE = 'C_NOTE_UPDATE_FAILURE';
export const C_NOTE_UPDATE_IS_IN_PROGRESS = 'C_NOTE_UPDATE_IS_IN_PROGRESS';

export const C_NOTE_EDITING_NEW_TITLE_VALUE = 'C_NOTE_EDITING_NEW_TITLE_VALUE';
export const C_NOTE_EDITING_NEW_CONTENT_VALUE = 'C_NOTE_EDITING_NEW_CONTENT_VALUE';
export const C_NOTE_EDITING_NEW_VALUES_RESTORE = 'C_NOTE_EDITING_NEW_VALUES_RESTORE';
export const C_NOTE_EDITING_ENABLE_TITLE_EDIT = 'C_NOTE_EDITING_ENABLE_TITLE_EDIT';

export const C_NOTE_CREATING_NEW_TITLE_VALUE = 'C_NOTE_CREATING_NEW_TITLE_VALUE';
export const C_NOTE_CREATING_NEW_CONTENT_VALUE = 'C_NOTE_CREATING_NEW_CONTENT_VALUE';
export const C_NOTE_CREATING_NEW_VALUES_RESTORE = 'C_NOTE_CREATING_NEW_VALUES_RESTORE';
